from .OfficialsControllers import OfficialsCtl
from .GoverningsControllers import GoverningsCtl
from .signUp import Authorization
from .controlPrensa import listAvisos
from .ImagenContriller import listaImages
from .dependenceController import listaDependence
from .fImageP import ImageCtl
#from .upFileController import upFile
from .AuthorController import AuthorCtl
from .AutotipeContoller import listAutotipo
from .NumeroController import NumeroCtl
from .controlPrensa2 import listAvisos2
