from .functionToken import fTocken
from .functionOfficials import dbOfficials
from .functionGovernings import dbGovernings
from .governingsType import fType
from .fUser import functionUser
from .fRoles import functionRole
from .listaPrensa import Avisos_list
from ..controllers import controlPrensa
from ..functions import Avisos_list